### ISSUE TITLE
Totem Can't Play YouTube Videos

### ISSUE THREAD

**Issue by Saroufim** [flathub/org.gnome.Totem#38]
When trying to play YouTube videos, it complains about a missing text/html codec.

**Comment by janxkoci** [comment]
Same issue. I started to see it also in non-flatpak version in Ubuntu 18.04 (which worked in the past) and I resolved it by installing `ubuntu-restricted-extras` package. The flathub version still throws the error though.

**Comment by hadess** [comment]
Fixed by https://github.com/flathub/org.gnome.Totem.Videosite.YouTubeDl
If it doesn't work, file bugs against this module.

**Comment by Saroufim** [comment]
It works wonderfully well now. Thanks.

**Comment by Umeaboy** [comment]
Does one have to use the flatpak in order to make this work?

**Comment by Umeaboy** [comment]
Seems like a package called libquvi solves this situation if you read this reply: https://bbs.archlinux.org/viewtopic.php?pid=1405353#p1405353

However, it doesn't solve it for me.

**Comment by hadess** [comment]
> Does one have to use the flatpak in order to make this work?

Yes. Or for your distribution to recreate the setup put in place by the Flatpak extension. The documentation for the mechanism is here:
https://gitlab.gnome.org/GNOME/totem-pl-parser/-/blob/master/plparse/README-videosite-script.md

> Seems like a package called libquvi solves this situation if you read this reply: https://bbs.archlinux.org/viewtopic.php?pid=1405353#p1405353
> 
> However, it doesn't solve it for me.

This is from 2014, the software's changed.
